### PR TITLE
Fix the Rust nightly build

### PR DESCRIPTION
**Pull request by mmatyas**
These changes make it possible to build the project using the latest Rust nightly (1.37 at the moment).

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
Can we upstream these fixes to the main WR?

**Comment by mmatyas** [comment]
I've just tried servo/webrender's master, but it seems to work fine with the current nightly, without any changes.

**Comment by kvark** [comment]
@mmatyas don't you find this weird then? If the upstream works fine, you should be able to fix this by just updating to latest instead of trying to fix it on your own.

**Comment by zakorgy** [comment]
I merge this, because this PR enables us to work with rust version 1.36 and higher.

**Pull request merged**
